import type { BacktestPhaseFilter } from '../types/backtest';
import type { AlertTargetScope, AlertType, MarketLightStatus, MarketRegion, PortfolioStopLossMode } from '../types/alerts';
import type { PortfolioCashDirection, PortfolioCorporateActionType, PortfolioSide } from '../types/portfolio';
import type { UiLanguage } from '../i18n/uiText';

type Option<T extends string = string> = { value: T; label: string };
const alertTypes: AlertType[] = ['price_cross', 'price_change_percent', 'volume_spike', 'ma_price_cross', 'rsi_threshold', 'macd_cross', 'kdj_cross', 'cci_threshold', 'portfolio_stop_loss', 'portfolio_concentration', 'portfolio_drawdown', 'portfolio_price_stale', 'market_light_status', 'market_light_score_drop'];
const symbolAlertTypes = alertTypes.slice(0, 8);
const portfolioAlertTypes = alertTypes.slice(8, 12);
const marketAlertTypes = alertTypes.slice(12);

export const BACKTEST_TEXT = {
  zh: { documentTitle: '策略回測 - DSA', codePlaceholder: '按股票代碼篩選（留空表示全部）', filter: '篩選', evalWindow: '評估窗口', phase: '階段', startDate: '開始日期', startDateAria: '分析開始日期', endDate: '結束日期', endDateAria: '分析結束日期', oneDayValidation: '1 日驗證', forceRerun: '強制重跑', running: '回測中...', runBacktest: '運行回測', oneDayModeDescription: '1 日驗證模式會用下一個交易日收盤表現校驗 AI 預測。', windowModeDescription: '將評估窗口設為 1，可查看 AI 預測與下一個交易日收盤表現的匹配情況。', overallPerformance: '整體表現', noMetricsTitle: '暫無指標', noMetricsDescription: '運行回測後會生成組合級表現指標。', loadingResults: '正在加載結果...', noResultsTitle: '暫無結果', noResultsDescription: '運行回測後可評估歷史分析準確性。', nextDayValidation: '次日驗證', resultSet: '結果集', allStocks: '全部股票', filteredStock: '篩選 {code}', dayWindow: '{days} 日窗口', fromDate: '自 {date}', toDate: '至 {date}', scrollHint: '小屏幕可橫向滾動', stock: '股票', analysisDate: '分析日期', aiPrediction: 'AI 預測', actualPerformance: '實際表現', windowReturn: '窗口收益', accuracy: '準確性', directionMatch: '方向匹配', result: '結果', status: '狀態', totalPage: '共 {total} 條結果 · 第 {page} / {pages} 頁', directionAccuracy: '方向準確率', winRate: '勝率', avgSimulatedReturn: '平均模擬收益', avgStockReturn: '平均個股收益', stopLossTriggerRate: '止損觸發率', takeProfitTriggerRate: '止盈觸發率', avgDaysToFirstHit: '平均命中天數', evaluationCount: '評估數', outcomeSummary: '盈 / 虧 / 中', phaseDistribution: '階段分佈：{text}', processed: '已處理:', saved: '已保存:', completed: '已完成:', insufficient: '數據不足:', errors: '錯誤:', yes: '是', no: '否', unknown: '未知' },
  en: { documentTitle: 'Strategy Backtest - DSA', codePlaceholder: 'Filter by stock code (leave empty for all)', filter: 'Filter', evalWindow: 'Evaluation window', phase: 'Phase', startDate: 'Start date', startDateAria: 'Analysis start date', endDate: 'End date', endDateAria: 'Analysis end date', oneDayValidation: '1D validation', forceRerun: 'Force rerun', running: 'Backtesting...', runBacktest: 'Run backtest', oneDayModeDescription: '1D validation checks AI predictions against the next trading day close.', windowModeDescription: 'Set the evaluation window to 1 to compare AI predictions with the next trading day close.', overallPerformance: 'Overall performance', noMetricsTitle: 'No metrics', noMetricsDescription: 'Portfolio-level performance metrics appear after a backtest runs.', loadingResults: 'Loading results...', noResultsTitle: 'No results', noResultsDescription: 'Run a backtest to evaluate historical analysis accuracy.', nextDayValidation: 'Next-day validation', resultSet: 'Result set', allStocks: 'All stocks', filteredStock: 'Filtered {code}', dayWindow: '{days}-day window', fromDate: 'from {date}', toDate: 'to {date}', scrollHint: 'Scroll horizontally on small screens', stock: 'Stock', analysisDate: 'Analysis date', aiPrediction: 'AI prediction', actualPerformance: 'Actual performance', windowReturn: 'Window return', accuracy: 'Accuracy', directionMatch: 'Direction match', result: 'Result', status: 'Status', totalPage: '{total} results · Page {page} / {pages}', directionAccuracy: 'Direction accuracy', winRate: 'Win rate', avgSimulatedReturn: 'Avg simulated return', avgStockReturn: 'Avg stock return', stopLossTriggerRate: 'Stop-loss trigger rate', takeProfitTriggerRate: 'Take-profit trigger rate', avgDaysToFirstHit: 'Avg days to first hit', evaluationCount: 'Evaluations', outcomeSummary: 'Win / Loss / Neutral', phaseDistribution: 'Phase breakdown: {text}', processed: 'Processed:', saved: 'Saved:', completed: 'Completed:', insufficient: 'Insufficient:', errors: 'Errors:', yes: 'Yes', no: 'No', unknown: 'Unknown' },
} as const;

export const BACKTEST_PHASE_FILTER_OPTIONS: Record<UiLanguage, Array<Option<BacktestPhaseFilter>>> = {
  zh: [{ value: 'all', label: '全部階段' }, { value: 'premarket', label: '盤前' }, { value: 'intraday', label: '盤中' }, { value: 'postmarket', label: '盤後' }, { value: 'unknown', label: '未知' }],
  en: [{ value: 'all', label: 'All phases' }, { value: 'premarket', label: 'Pre-market' }, { value: 'intraday', label: 'Intraday' }, { value: 'postmarket', label: 'Post-market' }, { value: 'unknown', label: 'Unknown' }],
};
export const BACKTEST_PHASE_LABELS: Record<UiLanguage, Record<string, string>> = { zh: { premarket: '盤前', intraday: '盤中', postmarket: '盤後', unknown: '未知' }, en: { premarket: 'Pre-market', intraday: 'Intraday', postmarket: 'Post-market', unknown: 'Unknown' } };
export const BACKTEST_OUTCOME_LABELS: Record<UiLanguage, Record<string, string>> = { zh: { win: '盈利', loss: '虧損', neutral: '中性' }, en: { win: 'Win', loss: 'Loss', neutral: 'Neutral' } };
export const BACKTEST_STATUS_LABELS: Record<UiLanguage, Record<string, string>> = { zh: { completed: '已完成', insufficient: '數據不足', insufficient_data: '數據不足', error: '錯誤' }, en: { completed: 'Completed', insufficient: 'Insufficient data', insufficient_data: 'Insufficient data', error: 'Error' } };
export const BACKTEST_MOVEMENT_LABELS: Record<UiLanguage, Record<string, string>> = { zh: { up: '上漲', down: '下跌', flat: '持平' }, en: { up: 'Up', down: 'Down', flat: 'Flat' } };
export const BACKTEST_DIRECTION_EXPECTED_LABELS: Record<UiLanguage, Record<string, string>> = { zh: { long: '做多', cash: '空倉', up: '看漲', down: '看跌', not_down: '不看跌', flat: '持平' }, en: { long: 'Long', cash: 'Cash', up: 'Bullish', down: 'Bearish', not_down: 'Not bearish', flat: 'Flat' } };

export const ALERT_TYPE_LABELS: Record<UiLanguage, Record<AlertType, string>> = {
  zh: { price_cross: '價格突破', price_change_percent: '漲跌幅', volume_spike: '成交量放大', ma_price_cross: '價格均線穿越', rsi_threshold: 'RSI 閾值', macd_cross: 'MACD 金叉/死叉', kdj_cross: 'KDJ 金叉/死叉', cci_threshold: 'CCI 閾值', portfolio_stop_loss: '組合止損', portfolio_concentration: '組合集中度', portfolio_drawdown: '組合回撤', portfolio_price_stale: '組合價格狀態', market_light_status: '大盤紅綠燈狀態', market_light_score_drop: '大盤紅綠燈分數下降' },
  en: { price_cross: 'Price crossing', price_change_percent: 'Price change', volume_spike: 'Volume spike', ma_price_cross: 'Price/MA crossing', rsi_threshold: 'RSI threshold', macd_cross: 'MACD cross', kdj_cross: 'KDJ cross', cci_threshold: 'CCI threshold', portfolio_stop_loss: 'Portfolio stop loss', portfolio_concentration: 'Portfolio concentration', portfolio_drawdown: 'Portfolio drawdown', portfolio_price_stale: 'Portfolio price status', market_light_status: 'Market traffic light status', market_light_score_drop: 'Market traffic light score drop' },
};
export const ALERT_SEVERITY_LABELS: Record<UiLanguage, Record<string, string>> = { zh: { info: '提示', warning: '警告', critical: '嚴重' }, en: { info: 'Info', warning: 'Warning', critical: 'Critical' } };
export const ALERT_SCOPE_LABELS: Record<UiLanguage, Record<AlertTargetScope, string>> = { zh: { single_symbol: '單標的', watchlist: '自選股', portfolio_holdings: '持倉標的', portfolio_account: '持倉賬戶', market: '大盤市場' }, en: { single_symbol: 'Single symbol', watchlist: 'Watchlist', portfolio_holdings: 'Portfolio holdings', portfolio_account: 'Portfolio account', market: 'Market' } };
export const ALERT_MARKET_REGION_LABELS: Record<UiLanguage, Record<MarketRegion, string>> = { zh: { cn: 'A 股', hk: '港股', us: '美股' }, en: { cn: 'A-shares', hk: 'Hong Kong', us: 'US' } };
export const ALERT_MARKET_LIGHT_STATUS_LABELS: Record<UiLanguage, Record<MarketLightStatus, string>> = { zh: { yellow: '黃燈', red: '紅燈' }, en: { yellow: 'Yellow', red: 'Red' } };
export const ALERT_DIRECTION_LABELS = {
  zh: { abovePrice: '上破', belowPrice: '下破', upChange: '上漲', downChange: '下跌', aboveThreshold: '上穿', belowThreshold: '下穿', bullishCross: '金叉', bearishCross: '死叉', stopLossNear: '接近止損', stopLossBreach: '已觸發止損' },
  en: { abovePrice: 'above', belowPrice: 'below', upChange: 'up', downChange: 'down', aboveThreshold: 'above', belowThreshold: 'below', bullishCross: 'bullish cross', bearishCross: 'bearish cross', stopLossNear: 'Near stop loss', stopLossBreach: 'Stop loss breached' },
} as const;
export const ALERT_LIST_TEXT = {
  zh: { title: '告警規則', subtitle: '{total} 條規則', enabledFilter: '啟停狀態', alertTypeFilter: '規則類型', loadingRules: '正在加載規則', emptyTitle: '暫無告警規則', emptyDescription: '創建規則後，後臺評估任務會按輪詢週期處理已啟用的告警。', rule: '規則', target: '目標', type: '類型', parameters: '參數', status: '狀態', cooldown: '冷卻', updatedAt: '更新時間', action: '操作', source: '來源：{source}', allAccounts: '全部賬戶', accountTarget: '賬戶 {target}', enabled: '已啟用', disabled: '已停用', coolingDown: '冷卻中', notCoolingDown: '未冷卻', childTargetCooldown: '子目標見觸發歷史', test: '測試', testing: '測試中', disabling: '停用中', enabling: '啟用中', disable: '停用', enable: '啟用', delete: '刪除', cancel: '取消', scoreDropAtLeast: 'Score 下降 >= {value}', deleteAria: '刪除 {name}', deleteTitle: '刪除告警規則', deleteMessage: '確認刪除「{name}」嗎？該操作不會刪除已有觸發歷史。' },
  en: { title: 'Alert rules', subtitle: '{total} rules', enabledFilter: 'Status', alertTypeFilter: 'Rule type', loadingRules: 'Loading rules', emptyTitle: 'No alert rules', emptyDescription: 'After rules are created, background evaluation processes enabled alerts on the polling schedule.', rule: 'Rule', target: 'Target', type: 'Type', parameters: 'Parameters', status: 'Status', cooldown: 'Cooldown', updatedAt: 'Updated', action: 'Actions', source: 'Source: {source}', allAccounts: 'All accounts', accountTarget: 'Account {target}', enabled: 'Enabled', disabled: 'Disabled', coolingDown: 'Cooling down', notCoolingDown: 'Not cooling down', childTargetCooldown: 'Per-target cooldowns are in trigger history', test: 'Test', testing: 'Testing', disabling: 'Disabling', enabling: 'Enabling', disable: 'Disable', enable: 'Enable', delete: 'Delete', cancel: 'Cancel', scoreDropAtLeast: 'Score drop >= {value}', deleteAria: 'Delete {name}', deleteTitle: 'Delete alert rule', deleteMessage: 'Delete "{name}"? Existing trigger history will be kept.' },
} as const;
export const ALERT_ENABLED_FILTER_OPTIONS: Record<UiLanguage, Array<Option<'all' | 'enabled' | 'disabled'>>> = { zh: [{ value: 'all', label: '全部狀態' }, { value: 'enabled', label: '已啟用' }, { value: 'disabled', label: '已停用' }], en: [{ value: 'all', label: 'All statuses' }, { value: 'enabled', label: 'Enabled' }, { value: 'disabled', label: 'Disabled' }] };
export const ALERT_TYPE_FILTER_OPTIONS: Record<UiLanguage, Array<Option<'all' | AlertType>>> = { zh: [{ value: 'all', label: '全部類型' }, ...alertTypes.map((value) => ({ value, label: ALERT_TYPE_LABELS.zh[value] }))], en: [{ value: 'all', label: 'All types' }, ...alertTypes.map((value) => ({ value, label: ALERT_TYPE_LABELS.en[value] }))] };
export const ALERT_FORM_TEXT = {
  zh: { accountLoadFailed: '賬戶加載失敗', allAccounts: '全部賬戶', cardTitle: '創建告警規則', cardSubtitle: 'Web 告警中心', ruleName: '規則名稱', ruleNamePlaceholder: '可選，例如 茅臺價格突破', targetScope: '目標範圍', targetCode: '標的代碼', target: '目標', marketRegion: '市場區域', account: '賬戶', ruleType: '規則類型', severity: '嚴重級別', direction: '方向', priceThreshold: '價格閾值', changePctThreshold: '漲跌幅閾值（%）', volumeMultiplier: '成交量放大倍數', crossDirection: '交叉方向', thresholdDirection: '閾值方向', maDirection: '穿越方向', maWindow: '均線週期', rsiPeriod: 'RSI 週期', rsiThreshold: 'RSI 閾值', fastPeriod: '快線週期', slowPeriod: '慢線週期', signalPeriod: '信號週期', kdjPeriod: 'KDJ 週期', kPeriod: 'K 平滑週期', dPeriod: 'D 平滑週期', cciPeriod: 'CCI 週期', cciThreshold: 'CCI 閾值', stopLossMode: '止損模式', triggerStatus: '觸發狀態', scoreDropThreshold: 'Score 下降閾值', enableAfterCreate: '創建後立即啟用', creating: '創建中...', create: '創建規則', positiveNumber: '{label}必須是大於 0 的數字', integerRange: '{label}必須是 {min} 到 {max} 的整數', required: '{label}不能為空', finiteNumber: '{label}必須是有效數字', rsiRange: 'RSI 閾值必須在 0 到 100 之間', requiredBarsLimit: '{label} 週期組合需要 {requiredBars} 根日線，最多支持 {max} 根', fastLessThanSlow: '快線週期必須小於慢線週期', noMarketStatus: '至少選擇一個紅綠燈狀態', invalidStockCode: '股票代碼格式不正確' },
  en: { accountLoadFailed: 'Account loading failed', allAccounts: 'All accounts', cardTitle: 'Create alert rule', cardSubtitle: 'Web alert center', ruleName: 'Rule name', ruleNamePlaceholder: 'Optional, e.g. Moutai price crossing', targetScope: 'Target scope', targetCode: 'Symbol', target: 'Target', marketRegion: 'Market region', account: 'Account', ruleType: 'Rule type', severity: 'Severity', direction: 'Direction', priceThreshold: 'Price threshold', changePctThreshold: 'Change threshold (%)', volumeMultiplier: 'Volume multiplier', crossDirection: 'Cross direction', thresholdDirection: 'Threshold direction', maDirection: 'Cross direction', maWindow: 'MA window', rsiPeriod: 'RSI period', rsiThreshold: 'RSI threshold', fastPeriod: 'Fast period', slowPeriod: 'Slow period', signalPeriod: 'Signal period', kdjPeriod: 'KDJ period', kPeriod: 'K smoothing period', dPeriod: 'D smoothing period', cciPeriod: 'CCI period', cciThreshold: 'CCI threshold', stopLossMode: 'Stop-loss mode', triggerStatus: 'Trigger status', scoreDropThreshold: 'Score drop threshold', enableAfterCreate: 'Enable immediately', creating: 'Creating...', create: 'Create rule', positiveNumber: '{label} must be a number greater than 0', integerRange: '{label} must be an integer from {min} to {max}', required: '{label} is required', finiteNumber: '{label} must be a valid number', rsiRange: 'RSI threshold must be between 0 and 100', requiredBarsLimit: '{label} requires {requiredBars} daily bars, up to {max} are supported', fastLessThanSlow: 'Fast period must be less than slow period', noMarketStatus: 'Select at least one traffic light status', invalidStockCode: 'Invalid stock code format' },
} as const;
export const ALERT_SYMBOL_TYPE_OPTIONS: Record<UiLanguage, Array<Option<AlertType>>> = { zh: symbolAlertTypes.map((value) => ({ value, label: ALERT_TYPE_LABELS.zh[value] })), en: symbolAlertTypes.map((value) => ({ value, label: ALERT_TYPE_LABELS.en[value] })) };
export const ALERT_PORTFOLIO_TYPE_OPTIONS: Record<UiLanguage, Array<Option<AlertType>>> = { zh: portfolioAlertTypes.map((value) => ({ value, label: ALERT_TYPE_LABELS.zh[value] })), en: portfolioAlertTypes.map((value) => ({ value, label: ALERT_TYPE_LABELS.en[value] })) };
export const ALERT_MARKET_TYPE_OPTIONS: Record<UiLanguage, Array<Option<AlertType>>> = { zh: marketAlertTypes.map((value) => ({ value, label: ALERT_TYPE_LABELS.zh[value] })), en: marketAlertTypes.map((value) => ({ value, label: ALERT_TYPE_LABELS.en[value] })) };
export const ALERT_TARGET_SCOPE_OPTIONS: Record<UiLanguage, Array<Option<AlertTargetScope>>> = { zh: Object.entries(ALERT_SCOPE_LABELS.zh).map(([value, label]) => ({ value: value as AlertTargetScope, label })), en: Object.entries(ALERT_SCOPE_LABELS.en).map(([value, label]) => ({ value: value as AlertTargetScope, label })) };
export const ALERT_SEVERITY_OPTIONS: Record<UiLanguage, Array<Option<'info' | 'warning' | 'critical'>>> = { zh: Object.entries(ALERT_SEVERITY_LABELS.zh).map(([value, label]) => ({ value: value as 'info' | 'warning' | 'critical', label })), en: Object.entries(ALERT_SEVERITY_LABELS.en).map(([value, label]) => ({ value: value as 'info' | 'warning' | 'critical', label })) };
export const ALERT_PRICE_DIRECTION_OPTIONS: Record<UiLanguage, Array<Option<'above' | 'below'>>> = { zh: [{ value: 'above', label: '上破' }, { value: 'below', label: '下破' }], en: [{ value: 'above', label: 'Crosses above' }, { value: 'below', label: 'Crosses below' }] };
export const ALERT_CHANGE_DIRECTION_OPTIONS: Record<UiLanguage, Array<Option<'up' | 'down'>>> = { zh: [{ value: 'up', label: '上漲達到' }, { value: 'down', label: '下跌達到' }], en: [{ value: 'up', label: 'Rises by' }, { value: 'down', label: 'Falls by' }] };
export const ALERT_THRESHOLD_DIRECTION_OPTIONS: Record<UiLanguage, Array<Option<'above' | 'below'>>> = { zh: [{ value: 'above', label: '上穿' }, { value: 'below', label: '下穿' }], en: [{ value: 'above', label: 'Crosses above' }, { value: 'below', label: 'Crosses below' }] };
export const ALERT_CROSS_DIRECTION_OPTIONS: Record<UiLanguage, Array<Option<'bullish_cross' | 'bearish_cross'>>> = { zh: [{ value: 'bullish_cross', label: '金叉' }, { value: 'bearish_cross', label: '死叉' }], en: [{ value: 'bullish_cross', label: 'Bullish cross' }, { value: 'bearish_cross', label: 'Bearish cross' }] };
export const ALERT_STOP_LOSS_MODE_OPTIONS: Record<UiLanguage, Array<Option<PortfolioStopLossMode>>> = { zh: [{ value: 'near', label: '接近止損' }, { value: 'breach', label: '已觸發止損' }], en: [{ value: 'near', label: 'Near stop loss' }, { value: 'breach', label: 'Stop loss breached' }] };
export const ALERT_MARKET_REGION_OPTIONS: Record<UiLanguage, Array<Option<MarketRegion>>> = { zh: [{ value: 'cn', label: 'A 股（cn）' }, { value: 'hk', label: '港股（hk）' }, { value: 'us', label: '美股（us）' }], en: [{ value: 'cn', label: 'A-shares (cn)' }, { value: 'hk', label: 'Hong Kong (hk)' }, { value: 'us', label: 'US (us)' }] };
export const ALERT_MARKET_LIGHT_STATUS_OPTIONS: Record<UiLanguage, Array<Option<MarketLightStatus>>> = { zh: [{ value: 'red', label: '紅燈' }, { value: 'yellow', label: '黃燈' }], en: [{ value: 'red', label: 'Red' }, { value: 'yellow', label: 'Yellow' }] };

export const PORTFOLIO_TEXT = {
  zh: { documentTitle: '持倉分析 - DSA', title: '持倉管理', description: '組合快照、手工錄入、CSV 導入與風險分析（支持全組合 / 單賬戶切換）', accountView: '賬戶視圖', allAccounts: '全部賬戶', costMethod: '成本口徑', fifo: '先進先出（FIFO）', avg: '均價成本（AVG）', collapseCreate: '收起新建', createAccount: '新建賬戶', deleteAccount: '刪除賬戶', deletingAccount: '刪除中...', deleteAccountTitle: '刪除持倉賬戶', deleteAccountConfirm: '確認刪除', deleteAccountMessage: '確認刪除賬戶 {name}（#{id}）嗎？刪除後該賬戶會從默認列表、快照、風險和錄入入口隱藏；歷史流水不會物理刪除。', refreshing: '刷新中...', refreshData: '刷新數據', noAccounts: '還沒有可用賬戶，請先創建賬戶後再錄入交易或導入 CSV。', riskDegraded: '風險模塊降級', operationHint: '操作提示', analysisTask: '分析任務', snapshotPartialTitle: '組合估值限制', totalEquity: '總權益', totalMarketValue: '總市值', totalCash: '總現金', fxStatus: '匯率狀態', refreshFx: '刷新匯率', stale: '過期', latest: '最新', fxRefreshResult: '匯率刷新結果', positionsTitle: '持倉明細', countItems: '共 {count} 項', noPositionsTitle: '當前無持倉數據', noPositionsDescription: '錄入交易或導入 CSV 後，這裡會展示按賬戶彙總的持倉明細。', account: '賬戶', code: '代碼', quantity: '數量', avgCost: '均價', lastPrice: '現價', marketValue: '市值', unrealizedPnl: '未實現盈虧', returnPct: '收益率', action: '操作', submitting: '提交中', analyze: '分析', sectorConcentration: '行業集中度分佈', positionConcentrationFallback: '行業數據暫不可用，當前展示個股集中度', noConcentrationTitle: '暫無集中度數據', noConcentrationDescription: '風險模塊完成計算後，這裡會展示行業或個股維度的集中度分佈。', displayScope: '展示口徑', sectorDimension: '行業維度', positionDimensionFallback: '個股維度（降級顯示）', sectorAlert: '板塊集中度告警', topWeight: 'Top1 權重', yes: '是', no: '否', writeBlocked: '當前處於“全部賬戶”視圖。為避免誤寫，請先選擇一個具體賬戶後再進行手工錄入或 CSV 提交。', drawdownMonitor: '回撤監控', maxDrawdown: '最大回撤', currentDrawdown: '當前回撤', alert: '告警', stopLossWarning: '止損接近預警', triggeredCount: '觸發數', nearCount: '接近數', scope: '口徑', accountCount: '賬戶數', currency: '計價幣種', costMethodShort: '成本法', aiRiskSignals: 'AI 風險信號', aiRiskUnavailable: '信號風險暫不可用', aiRiskTotal: '風險信號', sellSignals: '賣出', reduceSignals: '減倉', alertSignals: '預警', noAiRiskSignals: '暫無防禦型信號' },
  en: { documentTitle: 'Portfolio Analysis - DSA', title: 'Portfolio management', description: 'Portfolio snapshots, manual entries, CSV import, and risk analysis with full-portfolio or single-account views', accountView: 'Account view', allAccounts: 'All accounts', costMethod: 'Cost method', fifo: 'FIFO', avg: 'Average cost', collapseCreate: 'Collapse', createAccount: 'New account', deleteAccount: 'Delete account', deletingAccount: 'Deleting...', deleteAccountTitle: 'Delete portfolio account', deleteAccountConfirm: 'Delete account', deleteAccountMessage: 'Delete account {name} (#{id})? It will be hidden from default lists, snapshots, risk views, and entry forms; historical ledger rows are not physically deleted.', refreshing: 'Refreshing...', refreshData: 'Refresh data', noAccounts: 'No accounts are available. Create an account before entering trades or importing CSV files.', riskDegraded: 'Risk module degraded', operationHint: 'Operation hint', analysisTask: 'Analysis task', snapshotPartialTitle: 'Portfolio valuation limitations', totalEquity: 'Total equity', totalMarketValue: 'Total market value', totalCash: 'Total cash', fxStatus: 'FX status', refreshFx: 'Refresh FX', stale: 'Stale', latest: 'Current', fxRefreshResult: 'FX refresh result', positionsTitle: 'Positions', countItems: '{count} items', noPositionsTitle: 'No positions', noPositionsDescription: 'After you enter trades or import CSV data, account-level positions appear here.', account: 'Account', code: 'Code', quantity: 'Quantity', avgCost: 'Avg cost', lastPrice: 'Last price', marketValue: 'Market value', unrealizedPnl: 'Unrealized P/L', returnPct: 'Return', action: 'Action', submitting: 'Submitting', analyze: 'Analyze', sectorConcentration: 'Sector concentration', positionConcentrationFallback: 'Sector data unavailable; showing position concentration', noConcentrationTitle: 'No concentration data', noConcentrationDescription: 'Sector or position concentration appears after the risk module finishes.', displayScope: 'Display scope', sectorDimension: 'Sector', positionDimensionFallback: 'Position fallback', sectorAlert: 'Sector concentration alert', topWeight: 'Top1 weight', yes: 'Yes', no: 'No', writeBlocked: 'You are viewing all accounts. Select a specific account before manual entry or CSV submission to avoid writing to the wrong scope.', drawdownMonitor: 'Drawdown monitor', maxDrawdown: 'Max drawdown', currentDrawdown: 'Current drawdown', alert: 'Alert', stopLossWarning: 'Stop-loss proximity warning', triggeredCount: 'Triggered', nearCount: 'Near', scope: 'Scope', accountCount: 'Accounts', currency: 'Quote currency', costMethodShort: 'Cost method', aiRiskSignals: 'AI risk signals', aiRiskUnavailable: 'Signal risk unavailable', aiRiskTotal: 'Risk signals', sellSignals: 'Sell', reduceSignals: 'Reduce', alertSignals: 'Alert', noAiRiskSignals: 'No defensive signals' },
} as const;
export const PORTFOLIO_SIDE_LABELS: Record<UiLanguage, Record<PortfolioSide, string>> = { zh: { buy: '買入', sell: '賣出' }, en: { buy: 'Buy', sell: 'Sell' } };
export const PORTFOLIO_CASH_DIRECTION_LABELS: Record<UiLanguage, Record<PortfolioCashDirection, string>> = { zh: { in: '流入', out: '流出' }, en: { in: 'Inflow', out: 'Outflow' } };
export const PORTFOLIO_CORPORATE_ACTION_LABELS: Record<UiLanguage, Record<PortfolioCorporateActionType, string>> = { zh: { cash_dividend: '現金分紅', split_adjustment: '拆並股調整' }, en: { cash_dividend: 'Cash dividend', split_adjustment: 'Split adjustment' } };
